# cspell:ignore noreply pypa sdist

name: CD

on:
  create:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  documentation:
    name: Build documentation and run notebooks
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
          sudo apt-get -y install pandoc graphviz
      - name: Build documentation and run notebooks
        working-directory: docs
        env:
          EXECUTE_NB: YES
        run: make html
      - name: Test doctests in docstrings
        working-directory: docs
        run: make ignore-warnings=1 doctest

  style:
    name: Style checks
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[ci]
          sudo npm install -g cspell markdownlint-cli pyright
      - name: Perform style checks
        run: tox -e sty
      - name: Check spelling
        run: cspell $(git ls-files)
      - name: Lint Markdown files
        run: markdownlint .
      - name: Run pyright
        run: pyright

  push:
    name: Push to stable branch
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    needs:
      - documentation
      - style
    steps:
      - uses: actions/checkout@master
      - name: Push to stable branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:refs/heads/stable -f
