# cspell:ignore noreply prereleased pypa reqs

name: CD

on:
  release:
    types:
      - prereleased
      - released

jobs:
  documentation:
    name: Build documentation and run notebooks
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .reqs/doc.txt
          pip install .
          sudo apt-get -y install pandoc graphviz
      - name: Build documentation and run notebooks
        working-directory: docs
        env:
          EXECUTE_NB: YES
        run: make html
      - name: Test doctests in docstrings
        working-directory: docs
        run: make ignore-warnings=1 doctest

  style:
    name: Style checks
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .reqs/sty.txt
          pip install .
          sudo npm install -g cspell pyright
      - name: Perform style checks
        run: pre-commit run -a
      - name: Check spelling
        run: cspell $(git ls-files)
      - name: Run pyright
        run: pyright

  push:
    name: Push to stable branch
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-18.04
    needs:
      - documentation
      - style
    steps:
      - uses: actions/checkout@master
      - name: Push to stable branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:refs/heads/stable -f
