# cspell:ignore noreply prereleased

name: CD

on:
  release:
    types:
      - prereleased
      - released

jobs:
  push:
    name: Push to stable branch
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Push to stable branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git push origin HEAD:refs/heads/stable -f
