name: pytest

on:
  push:
    branches:
      - main
      - epic/*
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  pytest:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python-version:
          - "3.7"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: |
            ${{ github.workflow }}-${{ github.job }}-${{ matrix.os }}-py${{ matrix.python-version }}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg') }}
          path: |
            .pytest_cache
            ~/.cache/pip/
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c .constraints/py${{ matrix.python-version }}.txt -e .[test]
      - name: Run unit tests and doctests with pytest
        run: pytest -n auto --cov=pwa_pages --cov-report=xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: matrix.python-version == '3.7'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          # cspell:ignore unittests
          flags: unittests
