# cspell:ignore reqs

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  documentation:
    name: Build documentation and run notebooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/3.7/requirements-doc.txt
          pip install .
          sudo apt-get -y install pandoc graphviz
      - name: Build documentation and run notebooks
        working-directory: docs
        run: make html

  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/3.7/requirements-sty.txt
          pip install .
          sudo npm install -g cspell pyright
      - name: Perform style checks
        run: pre-commit run -a
      - name: Check spelling
        run: cspell --no-progress $(git ls-files)
      - name: Run pyright
        run: pyright
