# cspell:ignore markdownlint

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  documentation:
    name: Build and check documentation
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
          sudo apt-get -y install pandoc
      - name: Build HTML-pages
        run: make html

  style:
    name: Style checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          sudo npm install -g cspell markdownlint-cli
      - name: Perform style checks
        run: tox -e sty
      - name: Check spelling
        run: cspell $(git ls-files)
      - name: Lint Markdown files
        run: markdownlint .
