# cspell:ignore

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  documentation:
    name: Build documentation and run notebooks
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
          sudo apt-get -y install pandoc graphviz
      - name: Build documentation and run notebooks
        working-directory: docs
        run: make html

  style:
    name: Style checks
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[pre-commit]
          sudo npm install -g cspell markdownlint-cli pyright
      - name: Perform style checks
        run: pre-commit run -a
      - name: Check spelling
        run: cspell $(git ls-files)
      - name: Lint Markdown files
        run: markdownlint .
      - name: Run pyright
        run: pyright
